from django.db import models

# Create your models here.

#class Person(models.Model):
#    age = models.PositiveSmallIntegerField()
#    citizenship_choices = [(1, 'Singaporean'), (2, 'PR'), (3,'Foreigner')]
#    citizenship = models.CharField(max_length=12, choices=citizenship_choices)
#    annual_income = models.PositiveIntegerField()
#    total_spending_amount = models.PositiveIntegerField()

class CreditCards(models.Model):
    credit_card_id = models.PositiveSmallIntegerField(primary_key=True)
    credit_card_name = models.CharField(max_length=200, default='Unknown Credit Card Name')
    multiple_levels = models.PositiveSmallIntegerField()
    bank_name = models.CharField(max_length=200, default='Unknown Bank Name')
    card_type = models.CharField(max_length=200, default='Unknown Card Type')
    payment_networks = models.CharField(max_length=200, default='Unknown Payment Network')
    money_smart_link = models.CharField(max_length=200, default='https://www.google.com')
    official_link = models.CharField(max_length=200, default='https://www.google.com')
    age_min = models.CharField(max_length=200, default='0')
    age_max = models.CharField(max_length=200, default='999')
    gender_req = models.CharField(max_length=200, default='M')
    annual_income_singaporean_min = models.CharField(max_length=200, default='30000')
    annual_income_pr_min = models.CharField(max_length=200, default='30000')
    annual_income_foreigner_min = models.CharField(max_length=200, default='30000')
    foreign_currency_transaction_fee = models.CharField(max_length=200, default='0')
    annual_fee = models.CharField(max_length=200, default='0')
    annual_fee_waiver_min_spend = models.CharField(max_length=200, default='0')
    overall_points_cap = models.CharField(max_length=200, default='999999999')
    overall_points_min_spend = models.CharField(max_length=200, default='0')
    contactless_points_multiplier = models.CharField(max_length=200, default='0')
    contactless_points_cap = models.CharField(max_length=200, default='999999999')
    contactless_points_lot = models.CharField(max_length=200, default='1')
    dining_points_multiplier = models.CharField(max_length=200, default='0')
    dining_points_cap = models.CharField(max_length=200, default='999999999')
    dining_points_lot = models.CharField(max_length=200, default='1')
    entertainment_points_multiplier = models.CharField(max_length=200, default='0')
    entertainment_points_cap = models.CharField(max_length=200, default='999999999')
    entertainment_points_lot = models.CharField(max_length=200, default='1')
    foreign_points_multiplier = models.CharField(max_length=200, default='0')
    foreign_points_cap = models.CharField(max_length=200, default='999999999')
    foreign_points_lot = models.CharField(max_length=200, default='1')
    online_shopping_others_points_multiplier = models.CharField(max_length=200, default='0')
    online_shopping_others_points_cap = models.CharField(max_length=200, default='999999999')
    online_shopping_others_points_lot = models.CharField(max_length=200, default='1')
    online_shopping_hotels_and_flight_points_multiplier = models.CharField(max_length=200, default='0')
    online_shopping_hotels_and_flights_points_cap = models.CharField(max_length=200, default='999999999')
    online_shopping_hotels_and_flights_points_lot = models.CharField(max_length=200, default='1')
    retail_shopping_points_multiplier = models.CharField(max_length=200, default='0')
    retail_shopping_points_cap = models.CharField(max_length=200, default='999999999')
    retail_shopping_points_lot = models.CharField(max_length=200, default='1')
    points_to_miles_conversion = models.CharField(max_length=200, default='1')
    overall_cashback_cap = models.CharField(max_length=200, default='999999999')
    overall_cashback_min_spend = models.CharField(max_length=200, default='0')
    cash_cashback = models.CharField(max_length=200, default='0')
    bill_cashback_rate = models.CharField(max_length=200, default='0')
    bill_cashback_cap = models.CharField(max_length=200, default='999999999')
    bill_cashback_min_spend = models.CharField(max_length=200, default='0')
    contactless_cashback_rate = models.CharField(max_length=200, default='0')
    contactless_cashback_cap = models.CharField(max_length=200, default='999999999')
    contactless_cashback_min_spend = models.CharField(max_length=200, default='0')
    dining_cashback_rate = models.CharField(max_length=200, default='0')
    dining_cashback_cap = models.CharField(max_length=200, default='999999999')
    dining_cashback_min_spend = models.CharField(max_length=200, default='0')
    foreign_cashback_rate = models.CharField(max_length=200, default='0')
    foreign_cashback_cap = models.CharField(max_length=200, default='999999999')
    foreign_cashback_min_spend = models.CharField(max_length=200, default='0')
    groceries_overall_cashback_cap = models.CharField(max_length=200, default='999999999')
    groceries_others_cashback_rate = models.CharField(max_length=200, default='0')
    groceries_others_cashback_cap = models.CharField(max_length=200, default='999999999')
    groceries_others_cashback_min_spend = models.CharField(max_length=200, default='0')
    groceries_ntuc_cashback_rate = models.CharField(max_length=200, default='0')
    groceries_ntuc_cashback_cap = models.CharField(max_length=200, default='999999999')
    groceries_ntuc_cashback_min_spend = models.CharField(max_length=200, default='0')
    groceries_sheng_siong_cashback_rate = models.CharField(max_length=200, default='0')
    groceries_sheng_siong_cashback_cap = models.CharField(max_length=200, default='999999999')
    groceries_sheng_siong_cashback_min_spend = models.CharField(max_length=200, default='0')
    groceries_cold_storage_cashback_rate = models.CharField(max_length=200, default='0')
    groceries_cold_storage_cashback_cap = models.CharField(max_length=200, default='999999999')
    groceries_cold_storage_cashback_min_spend = models.CharField(max_length=200, default='0')
    groceries_giant_cashback_rate = models.CharField(max_length=200, default='0')
    groceries_giant_cashback_cap = models.CharField(max_length=200, default='999999999')
    groceries_giant_cashback_min_spend = models.CharField(max_length=200, default='0')
    online_shopping_overall_cashback_cap = models.CharField(max_length=200, default='999999999')
    online_shopping_others_cashback_rate = models.CharField(max_length=200, default='0')
    online_shopping_others_cashback_cap = models.CharField(max_length=200, default='999999999')
    online_shopping_others_cashback_min_spend = models.CharField(max_length=200, default='0')
    online_shopping_hotels_and_flights_cashback_rate = models.CharField(max_length=200, default='0')
    online_shopping_hotels_and_flights_cashback_cap = models.CharField(max_length=200, default='999999999')
    online_shopping_hotels_and_flights_cashback_min_spend = models.CharField(max_length=200, default='0')
    petrol_overal_cashback_cap = models.CharField(max_length=200, default='999999999')
    petrol_others_cashback_rate = models.CharField(max_length=200, default='0')
    petrol_others_cashback_cap = models.CharField(max_length=200, default='999999999')
    petrol_others_cashback_min_spend = models.CharField(max_length=200, default='0')
    petrol_esso_cashback_rate = models.CharField(max_length=200, default='0')
    petrol_esso_cashback_cap = models.CharField(max_length=200, default='999999999')
    petrol_esso_cashback_min_spend = models.CharField(max_length=200, default='0')
    petrol_caltex_cashback_rate = models.CharField(max_length=200, default='0')
    petrol_caltex_cashback_cap = models.CharField(max_length=200, default='999999999')
    petrol_caltex_cashback_min_spend = models.CharField(max_length=200, default='0')
    petrol_shell_cashback_rate = models.CharField(max_length=200, default='0')
    petrol_shell_cashback_cap = models.CharField(max_length=200, default='999999999')
    petrol_shell_cashback_min_spend = models.CharField(max_length=200, default='0')
    retail_shopping_cashback_rate = models.CharField(max_length=200, default='0')
    retail_shopping_cashback_cap = models.CharField(max_length=200, default='999999999')
    retail_shopping_cashback_min_spend = models.CharField(max_length=200, default='0')
    transport_cashback_rate = models.CharField(max_length=200, default='0')
    transport_cashback_cap = models.CharField(max_length=200, default='999999999')
    transport_cashback_min_spend = models.CharField(max_length=200, default='0')
