# Generated by Django 2.1.5 on 2019-02-24 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_income_singaporean_min', models.PositiveIntegerField()),
                ('annual_income_pr_min', models.PositiveIntegerField()),
                ('annual_income_foreigner_min', models.PositiveIntegerField()),
                ('age_min', models.PositiveSmallIntegerField()),
                ('age_max', models.PositiveSmallIntegerField()),
                ('total_spending_amount_min', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveSmallIntegerField()),
                ('citizenship', models.CharField(choices=[(1, 'Singaporean'), (2, 'PR'), (3, 'Foreigner')], max_length=12)),
                ('annual_income', models.PositiveIntegerField()),
                ('total_spending_amount', models.PositiveIntegerField()),
            ],
        ),
    ]
