# Generated by Django 2.1.5 on 2019-02-24 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recommender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcards',
            name='eligible',
            field=models.BooleanField(default=None),
        ),
    ]
