# Generated by Django 2.1.5 on 2019-02-24 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recommender', '0002_auto_20190224_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcards',
            name='eligible',
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
