# Generated by Django 2.1.5 on 2019-03-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recommender', '0003_auto_20190224_1116'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.RemoveField(
            model_name='creditcards',
            name='eligible',
        ),
        migrations.RemoveField(
            model_name='creditcards',
            name='id',
        ),
        migrations.RemoveField(
            model_name='creditcards',
            name='total_spending_amount_min',
        ),
        migrations.AddField(
            model_name='creditcards',
            name='annual_fee',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='creditcards',
            name='annual_fee_waiver_min_spend',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='creditcards',
            name='bank_name',
            field=models.CharField(default='Unknown Bank Name', max_length=200),
        ),
        migrations.AddField(
            model_name='creditcards',
            name='bill_cashback_cap',
            field=models.CharField(default='999999999', max_length=200),
        ),
        migrations.AddField(
            model_name='creditcards',
            name='bill_cashback_min_spend',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='creditcards',
            name='bill_cashback_rate',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='creditcards',
            name='card_type',
            field=models.CharField(default='Unknown Card Type', max_length=200),
        ),
        migrations.AddField(
            model_name='creditcards',
            name='cash_cashback',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='creditcards',
            name='contactless_cashback_cap',
            field=models.CharField(default='999999999', max_length=200),
        ),
        migrations.AddField(
            model_name='creditcards',
            name='contactless_cashback_min_spend',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='creditcards',
            name='contactless_cashback_rate',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='creditcards',
            name='contactless_points_cap',
            field=models.CharField(default='999999999', max_length=200),
        ),
        migrations.AddField(
            model_name='creditcards',
            name='contactless_points_lot',
            field=models.CharField(default='1', max_length=200),
        ),
        migrations.AddField(
            model_name='creditcards',
            name='contactless_points_multiplier',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='creditcards',
            name='credit_card_id',
            field=models.PositiveSmallIntegerField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditcards',
            name='dining_cashback_cap',
            field=models.CharField(default='999999999', max_length=200),
        ),
        migrations.AddField(
            model_name='creditcards',
            name='dining_cashback_min_spend',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='creditcards',
            name='dining_cashback_rate',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='creditcards',
            name='dining_points_cap',
            field=models.CharField(default='999999999', max_length=200),
        ),
        migrations.AddField(
            model_name='creditcards',
            name='dining_points_lot',
            field=models.CharField(default='1', max_length=200),
        ),
        migrations.AddField(
            model_name='creditcards',
            name='dining_points_multiplier',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='creditcards',
            name='entertainment_points_cap',
            field=models.CharField(default='999999999', max_length=200),
        ),
        migrations.AddField(
            model_name='creditcards',
            name='entertainment_points_lot',
            field=models.CharField(default='1', max_length=200),
        ),
        migrations.AddField(
            model_name='creditcards',
            name='entertainment_points_multiplier',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='creditcards',
            name='foreign_cashback_cap',
            field=models.CharField(default='999999999', max_length=200),
        ),
        migrations.AddField(
            model_name='creditcards',
            name='foreign_cashback_min_spend',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='creditcards',
            name='foreign_cashback_rate',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='creditcards',
            name='foreign_currency_transaction_fee',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='creditcards',
            name='foreign_points_cap',
            field=models.CharField(default='999999999', max_length=200),
        ),
        migrations.AddField(
            model_name='creditcards',
            name='foreign_points_lot',
            field=models.CharField(default='1', max_length=200),
        ),
        migrations.AddField(
            model_name='creditcards',
            name='foreign_points_multiplier',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='creditcards',
            name='gender_req',
            field=models.CharField(default='M', max_length=200),
        ),
        migrations.AddField(
            model_name='creditcards',
            name='groceries_cold_storage_cashback_cap',
            field=models.CharField(default='999999999', max_length=200),
        ),
        migrations.AddField(
            model_name='creditcards',
            name='groceries_cold_storage_cashback_min_spend',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='creditcards',
            name='groceries_cold_storage_cashback_rate',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='creditcards',
            name='groceries_giant_cashback_cap',
            field=models.CharField(default='999999999', max_length=200),
        ),
        migrations.AddField(
            model_name='creditcards',
            name='groceries_giant_cashback_min_spend',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='creditcards',
            name='groceries_giant_cashback_rate',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='creditcards',
            name='groceries_ntuc_cashback_cap',
            field=models.CharField(default='999999999', max_length=200),
        ),
        migrations.AddField(
            model_name='creditcards',
            name='groceries_ntuc_cashback_min_spend',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='creditcards',
            name='groceries_ntuc_cashback_rate',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='creditcards',
            name='groceries_others_cashback_cap',
            field=models.CharField(default='999999999', max_length=200),
        ),
        migrations.AddField(
            model_name='creditcards',
            name='groceries_others_cashback_min_spend',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='creditcards',
            name='groceries_others_cashback_rate',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='creditcards',
            name='groceries_overall_cashback_cap',
            field=models.CharField(default='999999999', max_length=200),
        ),
        migrations.AddField(
            model_name='creditcards',
            name='groceries_sheng_siong_cashback_cap',
            field=models.CharField(default='999999999', max_length=200),
        ),
        migrations.AddField(
            model_name='creditcards',
            name='groceries_sheng_siong_cashback_min_spend',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='creditcards',
            name='groceries_sheng_siong_cashback_rate',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='creditcards',
            name='money_smart_link',
            field=models.CharField(default='https://www.google.com', max_length=200),
        ),
        migrations.AddField(
            model_name='creditcards',
            name='multiple_levels',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditcards',
            name='official_link',
            field=models.CharField(default='https://www.google.com', max_length=200),
        ),
        migrations.AddField(
            model_name='creditcards',
            name='online_shopping_hotels_and_flight_points_multiplier',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='creditcards',
            name='online_shopping_hotels_and_flights_cashback_cap',
            field=models.CharField(default='999999999', max_length=200),
        ),
        migrations.AddField(
            model_name='creditcards',
            name='online_shopping_hotels_and_flights_cashback_min_spend',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='creditcards',
            name='online_shopping_hotels_and_flights_cashback_rate',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='creditcards',
            name='online_shopping_hotels_and_flights_points_cap',
            field=models.CharField(default='999999999', max_length=200),
        ),
        migrations.AddField(
            model_name='creditcards',
            name='online_shopping_hotels_and_flights_points_lot',
            field=models.CharField(default='1', max_length=200),
        ),
        migrations.AddField(
            model_name='creditcards',
            name='online_shopping_others_cashback_cap',
            field=models.CharField(default='999999999', max_length=200),
        ),
        migrations.AddField(
            model_name='creditcards',
            name='online_shopping_others_cashback_min_spend',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='creditcards',
            name='online_shopping_others_cashback_rate',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='creditcards',
            name='online_shopping_others_points_cap',
            field=models.CharField(default='999999999', max_length=200),
        ),
        migrations.AddField(
            model_name='creditcards',
            name='online_shopping_others_points_lot',
            field=models.CharField(default='1', max_length=200),
        ),
        migrations.AddField(
            model_name='creditcards',
            name='online_shopping_others_points_multiplier',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='creditcards',
            name='online_shopping_overall_cashback_cap',
            field=models.CharField(default='999999999', max_length=200),
        ),
        migrations.AddField(
            model_name='creditcards',
            name='overall_cashback_cap',
            field=models.CharField(default='999999999', max_length=200),
        ),
        migrations.AddField(
            model_name='creditcards',
            name='overall_cashback_min_spend',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='creditcards',
            name='overall_points_cap',
            field=models.CharField(default='999999999', max_length=200),
        ),
        migrations.AddField(
            model_name='creditcards',
            name='overall_points_min_spend',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='creditcards',
            name='payment_networks',
            field=models.CharField(default='Unknown Payment Network', max_length=200),
        ),
        migrations.AddField(
            model_name='creditcards',
            name='petrol_caltex_cashback_cap',
            field=models.CharField(default='999999999', max_length=200),
        ),
        migrations.AddField(
            model_name='creditcards',
            name='petrol_caltex_cashback_min_spend',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='creditcards',
            name='petrol_caltex_cashback_rate',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='creditcards',
            name='petrol_esso_cashback_cap',
            field=models.CharField(default='999999999', max_length=200),
        ),
        migrations.AddField(
            model_name='creditcards',
            name='petrol_esso_cashback_min_spend',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='creditcards',
            name='petrol_esso_cashback_rate',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='creditcards',
            name='petrol_others_cashback_cap',
            field=models.CharField(default='999999999', max_length=200),
        ),
        migrations.AddField(
            model_name='creditcards',
            name='petrol_others_cashback_min_spend',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='creditcards',
            name='petrol_others_cashback_rate',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='creditcards',
            name='petrol_overal_cashback_cap',
            field=models.CharField(default='999999999', max_length=200),
        ),
        migrations.AddField(
            model_name='creditcards',
            name='petrol_shell_cashback_cap',
            field=models.CharField(default='999999999', max_length=200),
        ),
        migrations.AddField(
            model_name='creditcards',
            name='petrol_shell_cashback_min_spend',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='creditcards',
            name='petrol_shell_cashback_rate',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='creditcards',
            name='points_to_miles_conversion',
            field=models.CharField(default='1', max_length=200),
        ),
        migrations.AddField(
            model_name='creditcards',
            name='retail_shopping_cashback_cap',
            field=models.CharField(default='999999999', max_length=200),
        ),
        migrations.AddField(
            model_name='creditcards',
            name='retail_shopping_cashback_min_spend',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='creditcards',
            name='retail_shopping_cashback_rate',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='creditcards',
            name='retail_shopping_points_cap',
            field=models.CharField(default='999999999', max_length=200),
        ),
        migrations.AddField(
            model_name='creditcards',
            name='retail_shopping_points_lot',
            field=models.CharField(default='1', max_length=200),
        ),
        migrations.AddField(
            model_name='creditcards',
            name='retail_shopping_points_multiplier',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='creditcards',
            name='transport_cashback_cap',
            field=models.CharField(default='999999999', max_length=200),
        ),
        migrations.AddField(
            model_name='creditcards',
            name='transport_cashback_min_spend',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='creditcards',
            name='transport_cashback_rate',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='creditcards',
            name='age_max',
            field=models.CharField(default='999', max_length=200),
        ),
        migrations.AlterField(
            model_name='creditcards',
            name='age_min',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='creditcards',
            name='annual_income_foreigner_min',
            field=models.CharField(default='30000', max_length=200),
        ),
        migrations.AlterField(
            model_name='creditcards',
            name='annual_income_pr_min',
            field=models.CharField(default='30000', max_length=200),
        ),
        migrations.AlterField(
            model_name='creditcards',
            name='annual_income_singaporean_min',
            field=models.CharField(default='30000', max_length=200),
        ),
    ]
